municipalities = [
    "Tijuana",
    "Iztapalapa",
    "León",
    "Puebla",
    "Ecatepec de Morelos",
    "Juárez",
    "Zapopan",
    "Guadalajara",
    "Gustavo A. Madero",
    "Monterrey",
    "Nezahualcóyotl",
    "Mexicali",
    "Querétaro",
    "Culiacán",
    "Mérida",
    "Aguascalientes",
    "Chihuahua",
    "Hermosillo",
    "San Luis Potosí",
    "Benito Juárez",
    "Toluca",
    "Saltillo",
    "Morelia",
    "Naucalpan de Juárez",
    "Acapulco de Juárez",
    "Álvaro Obregón",
    "Tlajomulco de Zúñiga",
    "Torreón",
    "Chimalhuacán",
    "Reynosa",
    "Tlalpan",
    "Durango",
    "San Pedro Tlaquepaque",
    "Centro",
    "Tlalnepantla de Baz",
    "Apodaca",
    "Guadalupe",
    "Coyoacán",
    "Veracruz",
    "Tuxtla Gutiérrez",
    "Irapuato",
    "Tonalá",
    "Cuautitlán Izcalli",
    "Tecámac",
    "Cuauhtémoc",
    "Ixtapaluca",
    "Matamoros",
    "Atizapán de Zaragoza",
    "Celaya",
    "Tultitlán",
    "Mazatlán",
    "Xalapa",
    "General Escobedo",
    "Juárez",  # (Nuevo León)
    "Ahome",
    "Ensenada",
    "Venustiano Carranza",
    "Xochimilco",
    "Cajeme",
    "Benito Juárez",  # (Ciudad de México)
    "Azcapotzalco",
    "Nicolás Romero",
    "Tepic",
    "Nuevo Laredo",
    "Miguel Hidalgo",
    "San Nicolás de los Garza",
    "Iztacalco",
    "Chalco",
    "García",
    "Tláhuac",
    "Valle de Chalco Solidaridad",
    "Cuernavaca",
    "Gómez Palacio",
    "Uruapan",
    "Tapachula",
    "Los Cabos",
    "Victoria",
    "Solidaridad",
    "Soledad de Graciano Sánchez",
    "Tehuacán",
    "Pachuca de Soto",
    "Coatzacoalcos",
    "Santa Catarina",
    "La Paz",
    "San Juan del Río",
    "Tampico",
    "Campeche",
    "Coacalco de Berriozábal",
    "La Paz",          # (Baja California Sur)
    "Puerto Vallarta",
    "Guasave",
    "Huixquilucan",
    "Chilpancingo de los Bravo",
    "Zumpango",
    "Texcoco",
    "Salamanca",
    "Oaxaca de Juárez",
    "Altamira",
    "Nogales",
    "Carmen"
]
