street_names = [
    "Calle 5 de Mayo",
    "Avenida 16 de Septiembre",
    "Boulevard Insurgentes Sur",
    "Calle Independencia",
    "Calle Benito Juárez",
    "Calle Hidalgo",
    "Calle Morelos",
    "Avenida Reforma",
    "Avenida Patriotismo",
    "Calle Madero",
    "Calzada Tlalpan",
    "Boulevard Miguel Hidalgo",
    "Avenida Universidad",
    "Calle 20 de Noviembre",
    "Avenida Las Américas",
    "Boulevard del Río",
    "Calle Vicente Guerrero",
    "Avenida Tecnológico",
    "Calle Pino Suárez",
    "Calzada Ignacio Zaragoza",
    "Calle Aquiles Serdán",
    "Calle Lázaro Cárdenas",
    "Calle Venustiano Carranza",
    "Avenida 2 de Abril",
    "Calle Allende",
    "Avenida Niños Héroes",
    "Avenida Constitución",
    "Calle Pedro Moreno",
    "Boulevard López Mateos",
    "Calle Melchor Ocampo",
    "Calle Montes de Oca",
    "Calle 27 de Septiembre",
    "Calle Narciso Mendoza",
    "Calle Simón Bolívar",
    "Calle José María Morelos",
    "Calle Aldama",
    "Calle Rayón",
    "Calle Arcos",
    "Calle Calvario",
    "Calle Loma Bonita",
    "Calle Vista Alegre",
    "Calle Primavera",
    "Calle del Bosque",
    "Calle Jardines",
    "Calle del Parque",
    "Calle de la Paz",
    "Avenida de las Rosas",
    "Calle Álvaro Obregón",
    "Calle Efraín González Luna",
    "Avenida Chapultepec",
    "Calle Tamaulipas",
    "Calle Veracruz",
    "Calle Yucatán",
    "Calle Jalisco",
    "Avenida Michoacán",
    "Calle Oaxaca",
    "Avenida Sinaloa",
    "Calle Campeche",
    "Calle Sonora",
    "Calle Durango",
    "Calle Zacatecas",
    "Calle Guanajuato",
    "Calle Querétaro",
    "Calle Nuevo León",
    "Calle Chiapas",
    "Calle Tabasco",
    "Calle Coahuila",
    "Calle Colima",
    "Calle Hidalgo #2",
    "Calle Morelia",
    "Calle Monterrey",
    "Avenida Oaxtepec",
    "Calle Salvador Novo",
    "Calle Octavio Paz",
    "Calle Juan Rulfo",
    "Calle Amado Nervo",
    "Calle Sor Juana Inés de la Cruz",
    "Calle Diego Rivera",
    "Calle Frida Kahlo",
    "Calle Rufino Tamayo",
    "Calle José Clemente Orozco",
    "Calle Saturnino Herrán",
    "Calle Alfredo Zalce",
    "Calle Manuel M. Ponce",
    "Calle Agustín Lara",
    "Calle Gabilondo Soler",
    "Calle Roberto Cantoral",
    "Calle Consuelo Velázquez",
    "Calle Silvestre Revueltas",
    "Calle Carlos Chávez",
    "Calle Pátzcuaro",
    "Calle Tequila",
    "Calle Tulum",
    "Calle Cancún",
    "Calle Holbox",
    "Calle Manzanillo",
    "Calle Acapulco",
    "Calle Valladolid",
    "Calle Dolores",
    "Avenida Paseo de la Reforma"
]

